name: Documentation Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: 'Deploy documentation'
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: jsmrcaga/action-netlify-deploy@v2.0.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.TOKEN_SECRET }}
          NETLIFY_SITE_ID: ${{ secrets.SITE_ID }}
          NETLIFY_DEPLOY_TO_PROD: true
          install_command: "npm run docs:install"
          build_command: "npm run docs:build"
          build_directory: "doc/website/build"
